title: Apples for Dinner
description: Curated art delivered seasonally
url: applesfordinner.com
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-seo-tag
