title: New framed art every season
description: AFD Subscription Box
url: applesfordinner.com
plugins:
  - jekyll-seo-tag
exclude:
  - app/
include:
  - _redirects
featured_blog:
  title: Outsourcing everyday life
  url: https://medium.com/@WeAreAFD/outsourcing-everyday-life-b71d7cd3e2e0
